### PR TITLE
Setup kafka broker & V2X-Hub

### PR DESCRIPTION
**Pull request by paulbourelly999**
Created docker-compose file to bring up kafka broker and v2x-hub carma-streets branch. Also included the mysql directory for the localhost.sql file and the script-credentials.sh to create v2x-hub users. To create a v2xhub user a .env file must be created in the carma-streets directory with `username=<username>' and 'password=<password>'. Included web directory for the php web UI for v2xhub and included MAP and log directories for volumes created by v2xhub

### CODE REVIEW

**Review by dan-du-car — COMMENTED** [review]
Remove files that are related to V2xHub

**Comment by paulbourelly999** [comment]
> Remove files that are related to V2xHub

These files are required to run V2X-Hub and its PHP web page. If we want to remove these we either make changes to V2X-Hub like create a custom PHP image with these files present or deploy them completely independently. I think we should talk about this since from what I can tell there is an effort to make carma-streets a term to contain V2X-Hub and our carma-streets work.

**Comment by paulbourelly999** [comment]
@dan-du-car  I removed all the volumes because I was able to create volume less PHP and MYSQL custom images on the usdotfhwaops docker hub. Currently they are implemented on the carma-streets V2X-Hub branch and seem to be working. I am going to squash these commits. Once circleCI has finished building the most recent carma-streets images you should be able to use this docker-compose file to bring up everything. I can send you the v2xhub login if you need it.

**Review by dan-du-car — APPROVED** [review]

**Comment by dan-du-car** [comment]
> @dan-du-car I removed all the volumes because I was able to create volume less PHP and MYSQL custom images on the usdotfhwaops docker hub. Currently they are implemented on the carma-streets V2X-Hub branch and seem to be working. I am going to squash these commits. Once circleCI has finished building the most recent carma-streets images you should be able to use this docker-compose file to bring up everything. I can send you the v2xhub login if you need it.

Looks good. Thanks!

**Pull request merged**
